# Generated by Django 4.2.7 on 2025-04-10 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_code', models.CharField(help_text='Please Enter Complaint Code', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('missing_type', models.CharField(choices=[('CAT', 'CAT'), ('EXAM', 'EXAM'), ('BOTH', 'Both')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_to_exam_officer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('employee_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Exam Officer', 'Exam Officer'), ('COD', 'COD')], max_length=50)),
                ('departments', models.ManyToManyField(to='tracker.department')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.department')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_number', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3')])),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=255)),
                ('courses', models.ManyToManyField(to='tracker.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.department')),
            ],
        ),
        migrations.CreateModel(
            name='YearOfStudy',
            fields=[
                ('study_year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracker.complaint')),
                ('cat_mark', models.IntegerField(blank=True, null=True)),
                ('exam_mark', models.IntegerField(blank=True, null=True)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('comment_by_cod', models.TextField(blank=True, null=True)),
                ('approved_by_cod', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOffering',
            fields=[
                ('offering_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.course')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.lecturer')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.semester')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.unit')),
                ('year_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.yearofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.program')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.program'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='tracker.lecturer'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.student'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='unit_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.unitoffering'),
        ),
        migrations.CreateModel(
            name='ArchivedComplaint',
            fields=[
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracker.complaint')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.lecturer')),
            ],
        ),
    ]
