# Generated by Django 4.2.7 on 2025-04-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedresponse',
            name='archivedcomplaint',
        ),
        migrations.RemoveField(
            model_name='response',
            name='complaint',
        ),
        migrations.AddField(
            model_name='response',
            name='response_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArchivedComplaint',
        ),
        migrations.DeleteModel(
            name='ArchivedResponse',
        ),
    ]
