# Generated by Django 4.2.7 on 2025-04-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_archivedresponse_archivedcomplaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='academic_year',
            field=models.ForeignKey(default=0.9995056846267919, on_delete=django.db.models.deletion.CASCADE, to='tracker.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='student',
            field=models.ForeignKey(default='COM/B/01-00109/2018', on_delete=django.db.models.deletion.CASCADE, to='tracker.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='unit_offering',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='tracker.unitoffering'),
            preserve_default=False,
        ),
    ]
